version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
      - PORT=${PORT}
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    networks:
      - nestjs

  postgres:
    build:
      context: ./src/shared/data-base
      dockerfile: Dockerfile
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - nestjs

volumes:
  postgres:
    name: nestjs

networks:
  nestjs:
