version: '3.8'
services:
  api:
    # container_name: ""
    # image: docker pull postgres:16.2-alpine
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src

  postgres:
    build:
      context: ./src/shared/data-base
      dockerfile: Dockerfile
    # container_name: postgres"
    # image: 'uladek-postgress'
    # image: postgres:16.2-alpine
    ports:
      - ${POSRGRESS_PORT}:${POSGRES_PORT}
    environment:
      # - ROOT_PASSWORD=${ROOT_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - POSTGRES_PORT=${POSTGRES_PORT}
