version: '3.5'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      # - 5432:5432
      - ${PROD_PORT}:${PROD_PORT}
    environment:
      # - PORT=5432
      - PORT=${PROD_PORT}
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
